#DO NOT EDIT THIS FILE

import main;
import datetime;

year = 0
month = 0
day = 0
hour = 0
minute = 0

d = datetime.datetime(year, month, day, hour + 6, minute)

def code():
    assert main.hellowWorld() == "Hello World!"

def late():
    assert datetime.datetime.now < d